title: Peter Marc Farrugia
description: Talks, writing, research and selected projects by Peter Marc Farrugia.
url: https://pytfarrugia-bit.github.io
baseurl: ""
lang: en-GB
markdown: kramdown
permalink: pretty
exclude:
  - README.md
